language: go

go:
    - 1.8.x
    - master

install:
    - go get github.com/golang/lint/golint
    - go get -d -v ./...

script:
    - go build -v
    - go vet ./...
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - go test -v ./...

after_success:
    - go test -bench=.
